/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pglebow' at '8/27/15 7:21 PM' with Gradle 2.5
 *
 * @author pglebow, @date 8/27/15 7:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
